/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.alibaba.dts.formats.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Character extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1775377444003683903L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Character\",\"namespace\":\"com.alibaba.dts.formats.avro\",\"fields\":[{\"name\":\"charset\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence charset;
  @Deprecated public java.nio.ByteBuffer value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Character() {}

  /**
   * All-args constructor.
   */
  public Character(java.lang.CharSequence charset, java.nio.ByteBuffer value) {
    this.charset = charset;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return charset;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: charset = (java.lang.CharSequence)value$; break;
    case 1: value = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'charset' field.
   */
  public java.lang.CharSequence getCharset() {
    return charset;
  }

  /**
   * Sets the value of the 'charset' field.
   * @param value the value to set.
   */
  public void setCharset(java.lang.CharSequence value) {
    this.charset = value;
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.nio.ByteBuffer getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.nio.ByteBuffer value) {
    this.value = value;
  }

  /**
   * Creates a new Character RecordBuilder.
   * @return A new Character RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Character.Builder newBuilder() {
    return new com.alibaba.dts.formats.avro.Character.Builder();
  }
  
  /**
   * Creates a new Character RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Character RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Character.Builder newBuilder(com.alibaba.dts.formats.avro.Character.Builder other) {
    return new com.alibaba.dts.formats.avro.Character.Builder(other);
  }
  
  /**
   * Creates a new Character RecordBuilder by copying an existing Character instance.
   * @param other The existing instance to copy.
   * @return A new Character RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Character.Builder newBuilder(com.alibaba.dts.formats.avro.Character other) {
    return new com.alibaba.dts.formats.avro.Character.Builder(other);
  }
  
  /**
   * RecordBuilder for Character instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Character>
    implements org.apache.avro.data.RecordBuilder<Character> {

    private java.lang.CharSequence charset;
    private java.nio.ByteBuffer value;

    /** Creates a new Builder */
    private Builder() {
      super(com.alibaba.dts.formats.avro.Character.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Character.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.charset)) {
        this.charset = data().deepCopy(fields()[0].schema(), other.charset);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Character instance
     * @param other The existing instance to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Character other) {
            super(com.alibaba.dts.formats.avro.Character.SCHEMA$);
      if (isValidValue(fields()[0], other.charset)) {
        this.charset = data().deepCopy(fields()[0].schema(), other.charset);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'charset' field.
      * @return The value.
      */
    public java.lang.CharSequence getCharset() {
      return charset;
    }

    /**
      * Sets the value of the 'charset' field.
      * @param value The value of 'charset'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Character.Builder setCharset(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.charset = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'charset' field has been set.
      * @return True if the 'charset' field has been set, false otherwise.
      */
    public boolean hasCharset() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'charset' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Character.Builder clearCharset() {
      charset = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Character.Builder setValue(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Character.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Character build() {
      try {
        Character record = new Character();
        record.charset = fieldSetFlags()[0] ? this.charset : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
