/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.alibaba.dts.formats.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Field extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 49929941316960932L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Field\",\"namespace\":\"com.alibaba.dts.formats.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"dataTypeNumber\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int dataTypeNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Field() {}

  /**
   * All-args constructor.
   */
  public Field(java.lang.CharSequence name, java.lang.Integer dataTypeNumber) {
    this.name = name;
    this.dataTypeNumber = dataTypeNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return dataTypeNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: dataTypeNumber = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'dataTypeNumber' field.
   */
  public java.lang.Integer getDataTypeNumber() {
    return dataTypeNumber;
  }

  /**
   * Sets the value of the 'dataTypeNumber' field.
   * @param value the value to set.
   */
  public void setDataTypeNumber(java.lang.Integer value) {
    this.dataTypeNumber = value;
  }

  /**
   * Creates a new Field RecordBuilder.
   * @return A new Field RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Field.Builder newBuilder() {
    return new com.alibaba.dts.formats.avro.Field.Builder();
  }
  
  /**
   * Creates a new Field RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Field RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Field.Builder newBuilder(com.alibaba.dts.formats.avro.Field.Builder other) {
    return new com.alibaba.dts.formats.avro.Field.Builder(other);
  }
  
  /**
   * Creates a new Field RecordBuilder by copying an existing Field instance.
   * @param other The existing instance to copy.
   * @return A new Field RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Field.Builder newBuilder(com.alibaba.dts.formats.avro.Field other) {
    return new com.alibaba.dts.formats.avro.Field.Builder(other);
  }
  
  /**
   * RecordBuilder for Field instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Field>
    implements org.apache.avro.data.RecordBuilder<Field> {

    private java.lang.CharSequence name;
    private int dataTypeNumber;

    /** Creates a new Builder */
    private Builder() {
      super(com.alibaba.dts.formats.avro.Field.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Field.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dataTypeNumber)) {
        this.dataTypeNumber = data().deepCopy(fields()[1].schema(), other.dataTypeNumber);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Field instance
     * @param other The existing instance to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Field other) {
            super(com.alibaba.dts.formats.avro.Field.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dataTypeNumber)) {
        this.dataTypeNumber = data().deepCopy(fields()[1].schema(), other.dataTypeNumber);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Field.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Field.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataTypeNumber' field.
      * @return The value.
      */
    public java.lang.Integer getDataTypeNumber() {
      return dataTypeNumber;
    }

    /**
      * Sets the value of the 'dataTypeNumber' field.
      * @param value The value of 'dataTypeNumber'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Field.Builder setDataTypeNumber(int value) {
      validate(fields()[1], value);
      this.dataTypeNumber = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'dataTypeNumber' field has been set.
      * @return True if the 'dataTypeNumber' field has been set, false otherwise.
      */
    public boolean hasDataTypeNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'dataTypeNumber' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Field.Builder clearDataTypeNumber() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Field build() {
      try {
        Field record = new Field();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.dataTypeNumber = fieldSetFlags()[1] ? this.dataTypeNumber : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
