/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.alibaba.dts.formats.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Timestamp extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9104952719193464206L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Timestamp\",\"namespace\":\"com.alibaba.dts.formats.avro\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"millis\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long timestamp;
  @Deprecated public int millis;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Timestamp() {}

  /**
   * All-args constructor.
   */
  public Timestamp(java.lang.Long timestamp, java.lang.Integer millis) {
    this.timestamp = timestamp;
    this.millis = millis;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return millis;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.lang.Long)value$; break;
    case 1: millis = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'millis' field.
   */
  public java.lang.Integer getMillis() {
    return millis;
  }

  /**
   * Sets the value of the 'millis' field.
   * @param value the value to set.
   */
  public void setMillis(java.lang.Integer value) {
    this.millis = value;
  }

  /**
   * Creates a new Timestamp RecordBuilder.
   * @return A new Timestamp RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Timestamp.Builder newBuilder() {
    return new com.alibaba.dts.formats.avro.Timestamp.Builder();
  }
  
  /**
   * Creates a new Timestamp RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Timestamp RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Timestamp.Builder newBuilder(com.alibaba.dts.formats.avro.Timestamp.Builder other) {
    return new com.alibaba.dts.formats.avro.Timestamp.Builder(other);
  }
  
  /**
   * Creates a new Timestamp RecordBuilder by copying an existing Timestamp instance.
   * @param other The existing instance to copy.
   * @return A new Timestamp RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Timestamp.Builder newBuilder(com.alibaba.dts.formats.avro.Timestamp other) {
    return new com.alibaba.dts.formats.avro.Timestamp.Builder(other);
  }
  
  /**
   * RecordBuilder for Timestamp instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Timestamp>
    implements org.apache.avro.data.RecordBuilder<Timestamp> {

    private long timestamp;
    private int millis;

    /** Creates a new Builder */
    private Builder() {
      super(com.alibaba.dts.formats.avro.Timestamp.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Timestamp.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.millis)) {
        this.millis = data().deepCopy(fields()[1].schema(), other.millis);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Timestamp instance
     * @param other The existing instance to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Timestamp other) {
            super(com.alibaba.dts.formats.avro.Timestamp.SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.millis)) {
        this.millis = data().deepCopy(fields()[1].schema(), other.millis);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Timestamp.Builder setTimestamp(long value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Timestamp.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'millis' field.
      * @return The value.
      */
    public java.lang.Integer getMillis() {
      return millis;
    }

    /**
      * Sets the value of the 'millis' field.
      * @param value The value of 'millis'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Timestamp.Builder setMillis(int value) {
      validate(fields()[1], value);
      this.millis = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'millis' field has been set.
      * @return True if the 'millis' field has been set, false otherwise.
      */
    public boolean hasMillis() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'millis' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Timestamp.Builder clearMillis() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Timestamp build() {
      try {
        Timestamp record = new Timestamp();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.millis = fieldSetFlags()[1] ? this.millis : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
